[profile.default]
src = 'src'
out = 'artifacts'
test = 'tests'
libs = ['lib']
remappings = [
    'carrot/=lib/carrot/contracts/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'tests/=tests/',
    'oz-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'oz/=lib/openzeppelin-contracts/contracts/'
]

[profile.production]
optimizer = true
optimizer_runs = 200

[profile.test]
test = 'tests'
optimizer = false
