[profile.default]
remappings = [
    'carrot/=lib/carrot/contracts/',
    'ds-test/=lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'oz-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/',
    'oz/=lib/openzeppelin-contracts/contracts/',
    'tests/=test/',
    'src/=src',
]
optimizer_runs = 200

[profile.production]
optimizer = true
via_ir = true
optimizer_runs = 1000000
